* DONE Ray tracing in One Weekend
  Completed <2020-02-06>.  We did the things. Done in time. Went
  pretty well. Some details on comments and the git commit messages.

* INACTIVE Better / different BVHs                                 :optional:
  Also implement at least a BVH that is slower to construct, but of
  better quality for use with static scenes.
* TODO Document how we follow & deviate from tutorials

* TODO More physically based model
** BRDF, PDF, & Importance sampling
   I.e. physically accurate sampling distributions.

* NEXT Improve metal material
  Consider complex fresnel coefficients.
* NEXT LIDAR

* NEXT Generalize

* INACTIVE Volumes (mist etc) :optional:

* INACTIVE Particles/billboards (snow etc) :optional:

* INACTIVE Rewrite host-code in Rust :optional:

* INACTIVE Futhark lexer for LaTeX syntax highlighting :optional:
* INACTIVE Investigate problems related to float errors
  E.g. "catastrophic cancellation". See PBR Book 3.9.
* INACTIVE Textures :optional:
* INACTIVE Normal- / bump maps :optional:
* NEXT Lens distortion
  Compare using post-processing distortion maps with somehow
  implementing the lens parameters in the ray tracer. Simplified test
  to justify us not implementing a complex lens system (the hypothesis
  is that distortion maps will do just fine).

  Use some simple model, something like OpenCVs radial distortion:
  https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html
* INACTIVE Ensure conservation of energy
  Make sure that the material models we use are all compatible and
  that conservation of energy holds. Maybe somewhat optional, as we're
  implementing a somewhat simplified system, but should still very
  much be considered.
